### ISSUE TITLE
Class 'Error' not found

### ISSUE THREAD

**Issue by Mdhesari** [cloudinary/cloudinary_php#134]
although I require all the files, I get this rare issue!

can anyone help me there?!

**Comment by marissa-masangcay** [comment]
Hi @Mdhesari,

This typically happens when there is an error trying to be thrown but you don't have the 'Error.php' file included. Can you try adding the line "require 'src/Error.php';" (adjust path if this is not where your Error file is located) in your script and let me know if this works for you? Thanks!

**Comment by Mdhesari** [comment]
hello and thank you for your approval.

it was worked for me and i really appreciate that!

I has to require once Error.php from API folder...

despite this minor problem I have another problem called  ' wrong file
identifier/HTTP URL specified ' when i transform some photos

2018-08-03 21:37 GMT+04:30 Marissa Masangcay <notifications@github.com>:

**Comment by marissa-masangcay** [comment]
Hi @Mdhesari,

Can you give me an example of what you're doing when you receive this error? 

For further discussion please also feel free to open a support ticket with us at support@cloudinary.com or at this link: https://support.cloudinary.com/hc/en-us/requests/new

**Comment by Mdhesari** [comment]
I defined my logo with sith decimal type and that was why it happened..
