### ISSUE TITLE
Wrong url format on download_zip_url method

### ISSUE THREAD

**Issue by pesseyjulien** [cloudinary/cloudinary_php#164]
Hi,

Trying to use the download_zip_url methode but it's returning a broken url format.

example : 

https://api.cloudinary.com/v1_1/hooohytob/image/generate_archive?mode=download&public_ids%5B%5D=invoices%2Finvoice-5c827df2c7496-2019-03-000018&target_format=zip×tamp=1552419958&signature=4368be2f22be53ba4cc8efe9ebb2f4430c2e1a1b&api_key=97758413193673

The '×tamp' should be '&timestamp'. 

Thanks in advance for your help,
Julien Pessey

**Comment by aditimadan-Cloudinary** [comment]
We are able to reproduce the issue. We will let you know once it is fixed. Thanks for reporting

**Comment by aditimadan-Cloudinary** [comment]
Sorry, I forgot to revert.
The problem seems to be html encoding, &times is translated to x
See:
https://stackoverflow.com/questions/16834320/using-times-word-in-html-changes-to-%C3%97
If you are putting the URL in some kind of HTML tag, it needs to be escaped.
We have a unit test: test_download_zip_url that works just fine.

**Comment by pesseyjulien** [comment]
Hi, I did not get back to you as well but it's now working indeed. Thanks !
