### ISSUE TITLE
PHP Fatal error:  undefined function cloudinary_url()

### ISSUE THREAD

**Issue by Ale-Digitale** [cloudinary/cloudinary_php#192]
Hello, i'm trying to use Cloudinary PHP. I downloaded the official Github's samples.

I've copied the **SRC** and **SAMPLES folders** and the **autoload.php** to my hosting FTP. ( i followed carefully the manual setup process, no using composer )

The directory structure on the server (PHP 7.3) is really simple:

WWWROOT
---- autoload.php
---- src/
---- samples/
------------- basic/
------------------- basic.php
------------------- settings.php

I've correctly configured the **settings.php** inside the basic folder with my Cloudinary account parameters.

Now, if i try to call the basic.php page, i get:

**PHP Fatal error:  Uncaught Error: Call to undefined function cloudinary_url()** on basic.php:107

This is line 107:

`<link rel="shortcut icon" href="<?php echo cloudinary_url('http://cloudinary.com/favicon.png', array('type' => 'fetch')); ?>"/>`

So, why it's not recognizing that **cloudinary_url** function ?

Please, help me, thank you

**Comment by aditimadan-Cloudinary** [comment]
Hi,

I have also replied on the forum and stackoverflow for future readers. Copying the same response here:  This error usually happens when the path is incorrect. The `samples` directory is supposedly at the same level as where your `vendor` folder is located. So I would suggest to move the `samples` folder there and give it a try again.

Best,

**Comment by Ale-Digitale** [comment]
Dear Aditi Madan, firstly, thank you for your prompt answer.

I read your instructions, but I don't understand...
is there supposed to be a "vendor" folder then ?

I'm asking this because I followed the instructions here:
https://cloudinary.com/documentation/php_integration#manual_installation

**Manual installation:**

- Download the latest sources from:
https://github.com/cloudinary/cloudinary_php/tarball/master.
 
- Copy the **src folder** and the **autoload.php** file into your PHP project and then include Cloudinary's PHP classes in your code

So, I just copied the SRC FOLDER and AUTOLOAD.PHP ( and SAMPLES folder too ) directly inside my root folder. Aren't them enough to run Cloudinary correctly ?

As I said, I did a manual setup, didn't use Composer ( isn't the "vendor" folder a composer's thing ? )

Please help, thank you !
Alex

**Comment by roeeba** [comment]
Hi @Ale-Digitale. The 'vendor' folder is indeed related to Composer. If you're installing the library manually, then you'll also have to manually add the dependencies of the sample projects in order to properly run them. `cloudinary_url` is part of `Helpers.php`. We went ahead and fixed the dependencies on both Basic and PhotoAlbum samples. Please checkout master to apply changes.

**Comment by Ale-Digitale** [comment]
@roeeba 

Yeah... I just downloaded it again, now it works perfectly !!! That was the problem !

Thank you so much to all of you !

**Comment by roeeba** [comment]
Glad we could help :)
