### ISSUE TITLE
Move PhotoAlbum sample from Mysql to Sqlite

### ISSUE THREAD

**Issue by tdutrion** [cloudinary/cloudinary_php#30]
Hi,

In order to make the PhotoAlbum sample easier to execute with no external dependencies, would it be possible to move away from Mysql that requires a server to a file based database such as Sqlite?

According to the [documentation](http://www.redbeanphp.com/connection), Redbean supports Sqlite so it should not be difficult. It basically require to change the settings file to the following line:

```php
R::setup('sqlite:' . __DIR__ . '/dbfile.db');
```

This will create the file if it does not exists or use it as database if it exists. The file should also be excluded from the repository (added in `.gitignore`).

**Note: it is the opposite of the best practice to use a local file to save data into, and the file can therefore be stored in `/tmp` on Unix based system, but it may not work on Windows systems**

**Comment by tocker** [comment]
@tdutrion, sorry for the long delay in my answer. 

Since MySQL is a common DB to be used with PHP (e.g. LAMP), it seems reasonable to use it in the sample project.
However if you (or any other contributor) wish to submit a PR for an sqlite configuration - preferably as a copy of Photo Album - we'll add it to the samples folder! 😃
