### ISSUE TITLE
non-static library in the future?

### ISSUE THREAD

**Issue by justintilson** [cloudinary/cloudinary_php#44]
Hey guys. Whoever coded this and wrote the docs clearly invested a lot of time and energy making all calls static. To the novice PHP coder, this may seem to make the library easier to use but in fact it does not when using your lib in the context of a modern dependency injection container (Symfony, Laravel, Pimple, etc). Having all static calls gets in the way test driven development as well.

Instantiated class variables with dependency injection is a much better approach.

Please resist any urge to make function calls static!

**Comment by artjomsimon** [comment]
Any update here?

**Comment by holtkamp** [comment]
probably combinable with https://github.com/cloudinary/cloudinary_php/issues/75, this library seems to have little attention of the maintainers

**Comment by roeeba** [comment]
Hey guys, I apologize for the very delayed response. 
Thank you very much for your feedback. We're planning to resolve this issue on our next library version, which is currently in its planning phase. We'll share an ETA as soon as we'll have one.

**Comment by cloudinaraz** [comment]
Just a quick update that version 2.0 of the plugin is already in the beta phase and is available [here](https://github.com/cloudinary/cloudinary_php/tree/2.0.0-beta).

**Comment by holtkamp** [comment]
@cloudinaraz in v2 the static use of the Configuration seems till mandatory. 

It would be nice to be able to handover a Configuration instance to for example MediaAsset::fromParams();

**Comment by cloudinaraz** [comment]
Hey @holtkamp, just so that I understand your use case, are you trying to instantiate multiple Cloudinary configuration objects (instead of using a Singleton), each associated with a different cloud under your parent account so then you can dynamically choose which cloud object to use with each separate asset call in your code?

**Comment by holtkamp** [comment]
Hoi @cloudinaraz, 

thanks for your swift reply: 

> are you trying to instantiate multiple Cloudinary configuration objects (instead of using a Singleton), each associated with a different cloud under your parent account so then you can dynamically choose which cloud object to use with each separate asset call in your code?

No. 

What I would prefer/expect is that the Cloudinary SDK does not "rely" on Configuration::instance() being invoked. In case that is not done, code like this will trigger an exception `Invalid configuration, please set up your environment`:
```php
echo \Cloudinary\Asset\Image::fromParams('somePublicAssetId', [
  'width' => 100,
  'height' => 100,
])->toUrl();
```

But nevermind my feedback: instead of using the static `fromParams` function of the assets, I found out the following approach seems to work properly when having (and actually using) a $cloudinaryConfiguration property: 

```php

$cloudinaryImageAsset = new \Cloudinary\Asset\Image('somePublicAssetId, $this->cloudinaryConfiguration);
$cloudinaryImageAsset->setTransformation(
  \Cloudinary\Transformation\Transformation::fromParams([
    'width' => 100,
    'height' => 100,
  ])
);
echo $cloudinaryImageAsset->toUrl();
```

Maybe it would be useful to add such an example to the documentation?
