### ISSUE TITLE
Class Cloudinary\Akamai defined twice

### ISSUE THREAD

**Issue by holtkamp** [cloudinary/cloudinary_php#60]
@tocker heads-up, after updating from ```1.5.0``` => ```1.6.0``` a warning was generated:

```
 - Updating cloudinary/cloudinary_php (1.5.0 => 1.6.0) 
 - Generating autoload files

Warning: Ambiguous class resolution, "Cloudinary\Akamai" was found in both "/Users/user/workspace/project/vendor/cloudinary/cloudinary_php/src/Akamai.php" and "/Users/user/workspace/project/vendor/cloudinary/cloudinary_php/src/Cloudinary/Akamai.php", the first will be used.
```

So ```Cloudinary\Akamai``` is defined twice in the same project... Is this on purpose?

**Comment by msvrtan** [comment]
We are getting same error, bit scared to use the version due to it :( 

Do you have any issues cause of it @holtkamp?

**Comment by SeanKnight** [comment]
This error is caused by the classmap autoload in composer.json. Both files live under the src directory, have the same namespace, and same class/trait name. I would recommend switching from classmap to a PSR-4 autoloader, and also getting rid of the require statement here: https://github.com/cloudinary/cloudinary_php/blob/master/src/Cloudinary.php#L2

**Comment by holtkamp** [comment]
@msvrtan no issues, the file that will be used contains the logic. The autoloading mechanism is a bit dated as pointed out by @SeanKnight

**Comment by tocker** [comment]
We'll release a fix very soon.
